server:
  port: 8070
spring:
   application:
      name: eureka-service
eureka:
  instance:
   hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#spring.application.name=eureka-service
#server.port=8070
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

#eureka.server.wait-time-in-ms-when-sync-empty=0
  